version: '3'
services:
  meuponto-mysql:
    container_name: meuponto-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: meuponto
      MYSQL_USER: meuponto
      MYSQL_PASSWORD: meuponto@jorgesebastiao
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - app-tier

  meuponto-dev:
    restart: always
    build: .
    container_name: meuponto-dev
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JDBC_DATABASE_NAME: meuponto
      JDBC_DATABASE_URL: meuponto-mysql
      JDBC_DATABASE_USERNAME: meuponto
      JDBC_DATABASE_PASSWORD: meuponto@jorgesebastiao
    ports:
      - 8080:8080
    depends_on:
      - meuponto-mysql
    links:
      - meuponto-mysql
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge