version: '3'
services:
  meuponto-mysql:
    container_name: meuponto-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: 'meuponto'
      MYSQL_USER: 'meuponto'
      MYSQL_PASSWORD: 'meuponto@jorgesebastiao'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - app-tier

  meuponto:
    image: mehiell/meuponto:latest
    container_name: meuponto-ws
    environment:
      SPRING_PROFILES_ACTIVE: prod
      WAIT_HOSTS: mysql:3306
    ports:
      - 8080:8080
    depends_on:
      - meuponto-mysql
    links:
      - meuponto-mysql
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge